### PR TITLE
fixed validation for priority

### PR DESCRIPTION
**Pull request by Schwitzd**
Fixed validation for parameter priority on resource_interface_bridge_port

### CODE REVIEW

**Review by vaerh — CHANGES_REQUESTED** [review]
Can you test the resource with the `Validation64k` validator?

ValidateFunc:     Validation64k,
DiffSuppressFunc: HexEqual,

**Comment by Schwitzd** [comment]
I will try to understand how to test it.. I simply copied from resource_interface_bridge that has the same priority parameter and works.

**Comment by vaerh** [comment]
You've made absolute working changes to the code and I was already thinking of asking you to test them :) But that's a big deal. If the changes are not very urgent for you,  I will test them and add them together with other additions.

**Comment by vaerh** [comment]
For memory
изображение

**Comment by Schwitzd** [comment]
No urgency is only a personal home project take your time :)

**Pull request closed without merging**
