### PR TITLE
Adjusted VRRP resource

### PR DESCRIPTION
**Pull request by danielnachtrub**

### CODE REVIEW

**Comment by danielnachtrub** [comment]
Update requests have failures with grp-member & grp-authority

`400, message: 'Bad Request', details: 'unknown parameter grp-member'`
 `400, message: 'Bad Request', details: 'unknown parameter grp-authority'`

**Comment by vaerh** [comment]
@danielnachtrub 
Daniel, I missed that PR. Did you manage to solve the problems with the resource operation after your changes or not?

**Comment by danielnachtrub** [comment]
Unfortunately I didn't have time yet. The issue occurs on patch. Is there a flag i can apply to ignore these fields on update?

**Comment by vaerh** [comment]
The easiest way to remove relevant fields from the serealization is to specify `DiffSuppressFunc: AlwaysPresentNotUserProvided,` in the conflicting attributes. And also remove the default values (if any).

**Pull request closed without merging**
