### PR TITLE
feat: Add support for /routing/ospf/interface-template, /routing/ospf/instance and /routing/ospf/area

### PR DESCRIPTION
**Pull request by mrhamburg**
See title. Somehow tests are **passing** when running them locally on vaerhme/routeros:v7.9, but **fail** during CI runs

### CODE REVIEW

**Comment by vaerh** [comment]
Thx! I looked at your changes and have some questions. I will finish the current project in the next couple of days and do a detailed review.

**Comment by vaerh** [comment]
@mrhamburg
Menno, what version of ROS do you use?
I have a feeling that if I fix the code for version 7.9, the provider will not work for you.

**Comment by mrhamburg** [comment]
@vaerh Versions used, just verified, all working:

- Docker Image: vaerhme/routeros:v7.9
- RoS: MikroTik RouterOS 7.9.2


All tests are passing locally:
image

**Comment by vaerh** [comment]
> all working

That's great!
I prepared small corrections to the pull request, can you allow me to edit it?
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by mrhamburg** [comment]
I believe that option is already checked, unless I'm looking at the wrong option:
image

**Comment by vaerh** [comment]
Hmm, I don't need access to secrets, but I can't commit changes to the pull request. I'll try that a little later.
Thanks!

**Comment by mrhamburg** [comment]
Nevermind, it has a bug:
https://github.com/orgs/community/discussions/5634

I have granted you access to my fork directly

**Review by vaerh — COMMENTED** [review]
Moved to #233

**Pull request closed without merging**
