### PR TITLE
feat(ipv6): added ipv6 filter data

### PR DESCRIPTION
**Pull request by danielnachtrub**

### CODE REVIEW

**Comment by danielnachtrub** [comment]
Hi @vaerh,

does this look fine to you?

**Comment by vaerh** [comment]
I apologize, I'm back. Tough time. I'll be watching for changes now, thanks!

**Comment by vaerh** [comment]
@danielnachtrub 
Please add test and example for ipv6 after release.

**Review by vaerh — APPROVED** [review]

**Pull request merged**
